version: '2'

services:
  factory:
    image: obitec/dstack-factory:3.5
    build:
      context: ./factory/3.5/
      dockerfile: Dockerfile
      args:
        - UID=${UID}
    volumes:
      - /srv/build/wheelhouse:/wheelhouse
      - /srv/build/archive:/archive
      - /srv/build/recipes:/app/
    environment:
      - HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial/
      - WHEELHOUSE=/wheelhouse
      - PIP_WHEEL_DIR=/wheelhouse
      - PIP_FIND_LINKS=/archive
      - VIRTUAL_ENV=/env
      - CEXT
      - RECIPE
      - BUILD_REQ

  runtime:
    image: obitec/dstack-runtime:3.5
    build:
      context: ./runtime/3.5/
      dockerfile: Dockerfile
